-- MySQL Script generated by MySQL Workbench
-- Fri Mar 17 20:43:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Kursant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Kursant` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Kursant` (
  `idKursant` INT NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(45) NOT NULL,
  `nazwisko` VARCHAR(45) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `dataUrodzenia` DATE NOT NULL,
  `pkk` VARCHAR(20) NOT NULL,
  `haslo` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`idKursant`),
  UNIQUE INDEX `idKursant_UNIQUE` (`idKursant` ASC) VISIBLE,
  UNIQUE INDEX `pkk_UNIQUE` (`pkk` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Pojazd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pojazd` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pojazd` (
  `idPojazd` INT NOT NULL AUTO_INCREMENT,
  `marka` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `nrRejestracyjny` VARCHAR(8) NOT NULL,
  `typ` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPojazd`),
  UNIQUE INDEX `idPojazd_UNIQUE` (`idPojazd` ASC) VISIBLE,
  UNIQUE INDEX `nrRejestracyjny_UNIQUE` (`nrRejestracyjny` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Instruktor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Instruktor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Instruktor` (
  `idInstruktor` INT NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(45) NOT NULL,
  `nazwisko` VARCHAR(45) NOT NULL,
  `dataUrodzenia` DATE NOT NULL,
  `telefon` INT NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `haslo` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`idInstruktor`),
  UNIQUE INDEX `idInstruktor_UNIQUE` (`idInstruktor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Jazdy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Jazdy` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Jazdy` (
  `idJazdy` INT NOT NULL AUTO_INCREMENT,
  `dataCzas` DATETIME NULL,
  `idPojazd` INT NOT NULL,
  `idInstruktor` INT NOT NULL,
  `idKursant` INT NOT NULL,
  PRIMARY KEY (`idJazdy`, `idPojazd`, `idInstruktor`),
  UNIQUE INDEX `idJazdy_UNIQUE` (`idJazdy` ASC) VISIBLE,
  INDEX `fk_Jazdy_Pojazd_idx` (`idPojazd` ASC) VISIBLE,
  INDEX `fk_Jazdy_Instruktor1_idx` (`idInstruktor` ASC) VISIBLE,
  INDEX `fk_Jazdy_Kursant1_idx` (`idKursant` ASC) VISIBLE,
  CONSTRAINT `fk_Jazdy_Pojazd`
    FOREIGN KEY (`idPojazd`)
    REFERENCES `mydb`.`Pojazd` (`idPojazd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jazdy_Instruktor1`
    FOREIGN KEY (`idInstruktor`)
    REFERENCES `mydb`.`Instruktor` (`idInstruktor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jazdy_Kursant1`
    FOREIGN KEY (`idKursant`)
    REFERENCES `mydb`.`Kursant` (`idKursant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Opinie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Opinie` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Opinie` (
  `idOpinie` INT NOT NULL AUTO_INCREMENT,
  `ocena` INT NOT NULL,
  `trescOpinii` VARCHAR(128) NULL,
  `idKursant` INT NOT NULL,
  PRIMARY KEY (`idOpinie`, `idKursant`),
  UNIQUE INDEX `idOpinie_UNIQUE` (`idOpinie` ASC) VISIBLE,
  INDEX `fk_Opinie_Kursant1_idx` (`idKursant` ASC) VISIBLE,
  CONSTRAINT `fk_Opinie_Kursant1`
    FOREIGN KEY (`idKursant`)
    REFERENCES `mydb`.`Kursant` (`idKursant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MaterialyDydaktyczne`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MaterialyDydaktyczne` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MaterialyDydaktyczne` (
  `idMaterialyDydaktyczne` INT NOT NULL AUTO_INCREMENT,
  `plik` VARCHAR(45) NULL,
  `nazwa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMaterialyDydaktyczne`),
  UNIQUE INDEX `idMaterialyDydaktyczne_UNIQUE` (`idMaterialyDydaktyczne` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EwidencjaKursow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EwidencjaKursow` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EwidencjaKursow` (
  `idEwidencjaKursow` INT NOT NULL AUTO_INCREMENT,
  `kategoria` VARCHAR(2) NOT NULL,
  `cena` FLOAT NOT NULL,
  PRIMARY KEY (`idEwidencjaKursow`),
  UNIQUE INDEX `idEwidencjaKursow_UNIQUE` (`idEwidencjaKursow` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BazaPytan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BazaPytan` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BazaPytan` (
  `idPytania` INT NOT NULL AUTO_INCREMENT,
  `tresc` VARCHAR(256) NOT NULL,
  `odpowiedz1` VARCHAR(256) NOT NULL,
  `odpowiedz2` VARCHAR(256) NULL,
  `odpowiedz3` VARCHAR(256) NULL,
  `poprawnaOdpowiedz` VARCHAR(256) NOT NULL,
  `punktyPytania` INT NOT NULL,
  PRIMARY KEY (`idPytania`),
  UNIQUE INDEX `idPytania_UNIQUE` (`idPytania` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`WynikiTest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`WynikiTest` ;

CREATE TABLE IF NOT EXISTS `mydb`.`WynikiTest` (
  `idWynikiTest` INT NOT NULL AUTO_INCREMENT,
  `wynik` INT NULL,
  `idKursant` INT NOT NULL,
  PRIMARY KEY (`idWynikiTest`, `idKursant`),
  UNIQUE INDEX `idWynikiTest_UNIQUE` (`idWynikiTest` ASC) VISIBLE,
  INDEX `fk_WynikiTest_Kursant1_idx` (`idKursant` ASC) VISIBLE,
  CONSTRAINT `fk_WynikiTest_Kursant1`
    FOREIGN KEY (`idKursant`)
    REFERENCES `mydb`.`Kursant` (`idKursant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`ZapisanyKursant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ZapisanyKursant` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ZapisanyKursant` (
  `iidEwidencjaKursow` INT NOT NULL,
  `iidKursant` INT NOT NULL,
  PRIMARY KEY (`iidEwidencjaKursow`, `iidKursant`),
  INDEX `fk_EwidencjaKursow_has_Kursant_Kursant1_idx` (`iidKursant` ASC) VISIBLE,
  INDEX `fk_EwidencjaKursow_has_Kursant_EwidencjaKursow1_idx` (`iidEwidencjaKursow` ASC) VISIBLE,
  CONSTRAINT `fk_EwidencjaKursow_has_Kursant_EwidencjaKursow1`
    FOREIGN KEY (`iidEwidencjaKursow`)
    REFERENCES `mydb`.`EwidencjaKursow` (`idEwidencjaKursow`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EwidencjaKursow_has_Kursant_Kursant1`
    FOREIGN KEY (`iidKursant`)
    REFERENCES `mydb`.`Kursant` (`idKursant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UprawnieniaInstruktor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`UprawnieniaInstruktor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`UprawnieniaInstruktor` (
  `idEwidencjaKursow` INT NOT NULL,
  `idInstruktor` INT NOT NULL,
  PRIMARY KEY (`idEwidencjaKursow`, `idInstruktor`),
  INDEX `fk_EwidencjaKursow_has_Instruktor_Instruktor1_idx` (`idInstruktor` ASC) VISIBLE,
  INDEX `fk_EwidencjaKursow_has_Instruktor_EwidencjaKursow1_idx` (`idEwidencjaKursow` ASC) VISIBLE,
  CONSTRAINT `fk_EwidencjaKursow_has_Instruktor_EwidencjaKursow1`
    FOREIGN KEY (`idEwidencjaKursow`)
    REFERENCES `mydb`.`EwidencjaKursow` (`idEwidencjaKursow`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EwidencjaKursow_has_Instruktor_Instruktor1`
    FOREIGN KEY (`idInstruktor`)
    REFERENCES `mydb`.`Instruktor` (`idInstruktor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PrzypisaneMaterialy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PrzypisaneMaterialy` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PrzypisaneMaterialy` (
  `idMaterialyDydaktyczne` INT NOT NULL,
  `idEwidencjaKursow` INT NOT NULL,
  PRIMARY KEY (`idMaterialyDydaktyczne`, `idEwidencjaKursow`),
  INDEX `fk_MaterialyDydaktyczne_has_EwidencjaKursow_EwidencjaKursow_idx` (`idEwidencjaKursow` ASC) VISIBLE,
  INDEX `fk_MaterialyDydaktyczne_has_EwidencjaKursow_MaterialyDydakt_idx` (`idMaterialyDydaktyczne` ASC) VISIBLE,
  CONSTRAINT `fk_MaterialyDydaktyczne_has_EwidencjaKursow_MaterialyDydaktyc1`
    FOREIGN KEY (`idMaterialyDydaktyczne`)
    REFERENCES `mydb`.`MaterialyDydaktyczne` (`idMaterialyDydaktyczne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MaterialyDydaktyczne_has_EwidencjaKursow_EwidencjaKursow1`
    FOREIGN KEY (`idEwidencjaKursow`)
    REFERENCES `mydb`.`EwidencjaKursow` (`idEwidencjaKursow`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
